@startuml
scale 3
top to bottom direction

actor "Project Owner" as Owner
actor "Admin" as Admin
actor "Backend" as Back

rectangle "Create New Project" {
  usecase "Create New Project" as UC3
  usecase "Upload Floorplan PDFs" as UC3a
  usecase "Assign Contractors" as UC3b
}

UC3 -[hidden]down-> UC3a
UC3a -[hidden]down-> UC3b

Owner --> UC3
Admin --> UC3

UC3 .> UC3a : <<include>>
UC3 .> UC3b : <<include>>
UC3a --> Back : saves uploaded files
UC3b --> Back : saves assignments

@enduml
