@startuml
scale 3
top to bottom direction

actor "Subcontractor" as Sub
actor "Contractor" as Con
actor "Project Owner" as Owner
actor "Admin" as Admin
actor "User" as User
actor "Backend" as Back

Sub --|> User
Con --|> User
Owner --|> User
Admin --|> User


rectangle "Log In" {
  usecase "Log In" as UC1
  usecase "Verify Details" as UC1a
  usecase "Display Login Error(s)" as UC1b
}

UC1 -[hidden]down-> UC1a
UC1a -[hidden]down-> UC1b

User --> UC1
UC1 .> UC1a : <<include>>
UC1b .> UC1 : <<extend>>
UC1a --> Back : queries credentials

@enduml
