@startuml
scale 3
top to bottom direction

actor "Subcontractor" as Sub
actor "Contractor" as Con
actor "Project Owner" as Owner
actor "Admin" as Admin
actor "User" as User

Sub --|> User
Con --|> User
Owner --|> User
Admin --|> User

rectangle "Punchlist Software - Overview" {
  usecase "Create Account" as UC0
  usecase "Log In" as UC1
  usecase "Main Dashboard" as UC2
  usecase "Create New Project" as UC3
  usecase "View Specific Project" as UC5
  usecase "Edit Project" as UC4
}

UC0 -[hidden]down-> UC1
UC1 -[hidden]down-> UC2
UC2 -[hidden]down-> UC3
UC3 -[hidden]down-> UC5
UC5 -[hidden]down-> UC4


User --> UC0
User --> UC1
User --> UC2
User --> UC5

UC5 .> UC4 : <<extend>>

Owner --> UC3
Admin --> UC3
User --> UC4 : With Limitations Based on Permissions

@enduml
