@startuml
scale 2
top to bottom direction

actor "Project Owner" as Owner
actor "Admin" as Admin
actor "Subcontractor" as Sub
actor "Contractor" as Con
actor "User" as User
actor "Backend" as Back

Sub --|> User
Con --|> User
Owner --|> User
Admin --|> User

rectangle "View / Edit Project" {
  usecase "View Specific Project" as UC5
  usecase "Show Floorplan PDFs With Task Stamps on Each" as UC5a
  usecase "Filters" as UC5b

  usecase "Edit Project" as UC4
  usecase "Add/Remove Contractors" as UC4a
  usecase "Add/Remove Subcontractors" as UC4b
  usecase "Add/Remove Tasks" as UC4c
  usecase "Edit Task Status" as UC4d
  usecase "Add/Remove Attachments" as UC4e
  usecase "Upload Additional Floorplans" as UC4f
}

' --- Group: View Specific Project ---
UC5 -[hidden]down-> UC5a
UC5a -[hidden]down-> UC5b

' --- Group: Edit Project ---
UC4 -[hidden]down-> UC4a
UC4a -[hidden]down-> UC4b
UC4b -[hidden]down-> UC4c
UC4c -[hidden]down-> UC4d
UC4d -[hidden]down-> UC4e
UC4e -[hidden]down-> UC4f

' --- Keep groups side by side ---
UC5 -[hidden]right-> UC4

User --> UC5
UC5 .> UC5a : <<include>>
UC5a --> Back

UC5b .> UC5 : <<extend>>
UC5b .> UC5a : <<extend>>

' Editing extends off viewing a project
UC4 .> UC5 : <<extend>>



' Owner/Admin only
UC4a .> UC4 : <<extend>>

' Owner/Admin/Contractor
UC4b .> UC4 : <<extend>>
Con --> UC4b
UC4c .> UC4 : <<extend>>
Con --> UC4c

note right of Con
  Contractor/Subcontractor arrows represent
  permitted actions either these actors can
  do under 'Edit Project'
end note

' Owner/Admin/Contractor/Subcontractor
UC4d .> UC4 : <<extend>>
Con --> UC4d
Sub --> UC4d
UC4e .> UC4 : <<extend>>
Con --> UC4e
Sub --> UC4e

' Owner/Admin only - uploading additional floorplans
UC4f .> UC4 : <<extend>>
Owner --> UC4f
Admin --> UC4f

note bottom of UC4f
  Contractor/Subcontractor cannot
  upload additional floorplans
end note

UC4a --> Back
UC4b --> Back
UC4c --> Back
UC4d --> Back
UC4e --> Back
UC4f --> Back

@enduml
